In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
import warnings
warnings.simplefilter('ignore')

In [2]:
df=pd.read_csv(r"C:\Users\shaba\OneDrive\csv_xml_sheets\Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [5]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [6]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [8]:
X= pd.get_dummies(df.drop('Exited',axis=1), drop_first=True)

In [9]:
y= df['Exited']

# train test split

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.2)

In [11]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

X_train= sc.fit_transform(X_train)

X_test=sc.transform(X_test)

# modelling

In [12]:
from keras.models import Sequential

In [13]:
ann = Sequential()

## adding input layers and first hidden layers

In [14]:
from keras.layers import Dense

In [15]:
ann.add(Dense(input_dim= 11, units= 6, kernel_initializer= 'uniform',activation = 'relu'))

In [16]:
# adding second hidden layer

In [17]:
ann.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# adding output layer
ann.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


# compailing ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics= ['accuracy'])

# training the Ann on training set

In [19]:
ann.fit(X_train,y_train,epochs =100,batch_size = 32)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7886 - loss: 0.6485
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8045 - loss: 0.4285
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.8078 - loss: 0.4054
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7918 - loss: 0.4190  
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.8001 - loss: 0.3959
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7967 - loss: 0.4056
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8332 - loss: 0.3938
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8255 - loss: 0.3960
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.8241 - loss: 0.3901
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8276 - loss: 0.3894
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8274 - loss: 0.3765  
Epoch 12/100
250/250 ━━━━━━━

In [20]:
y_train

7389    0
9275    0
2995    0
5316    0
356     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    1
Name: Exited, Length: 8000, dtype: int64

# prediction and evaluation

In [21]:
train_prediction = ann.predict(X_train)
test_prediction = ann.predict(X_test)


250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  


In [22]:
test_prediction

array([[0.37883592],
       [0.3460598 ],
       [0.166354  ],
       ...,
       [0.26936096],
       [0.1980123 ],
       [0.22370848]], dtype=float32)

In [23]:
test_prediction = (test_prediction>=0.5)
train_prediction = (train_prediction>=0.5)

In [24]:
test_prediction

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix

print('test accuracy:', accuracy_score(y_test,test_prediction))
print('train accuracy:', accuracy_score(y_train,train_prediction))
confusion_matrix(y_test,test_prediction)

test accuracy: 0.8585
train accuracy: 0.860625


array([[1517,   78],
       [ 205,  200]])

# cross validation 

In [26]:
def built_cross_classifier():
    classifier = Sequential()
    classifier.add(Dense(input_dim=11, units=6,kernel_initializer= 'uniform', activation = 'relu'))
    classifier.add(Dense(units=6,kernel_initializer= 'uniform', activation = 'relu'))
    classifier.add(Dense(units=1,kernel_initializer= 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics= ['accuracy'])   
    return classifier

In [27]:
from scikeras.wrappers import KerasClassifier


In [28]:
classifier = KerasClassifier(built_cross_classifier, batch_size = 10,epochs = 50)

In [29]:
from sklearn.model_selection import cross_val_score
score= cross_val_score(classifier,X,y,cv = 5)
print (score)
score.mean()

Epoch 1/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7911 - loss: 0.5541
Epoch 2/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7967 - loss: 0.5287
Epoch 3/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7985 - loss: 0.5204
Epoch 4/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.7953 - loss: 0.5180
Epoch 5/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7926 - loss: 0.5193
Epoch 6/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7841 - loss: 0.5310
Epoch 7/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 992us/step - accuracy: 0.7964 - loss: 0.5151
Epoch 8/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7937 - loss: 0.5154
Epoch 9/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - accuracy: 0.7877 - loss: 0.5200
Epoch 10/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 957us/step - accuracy: 0.7978 - loss: 0.5081
Epoch 11/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7986 - loss: 0.5005  
Epoch 12/50
800/800 ━━━━━━━━━━━━━━━━━━

np.float64(0.7963)

In [30]:
classifier = KerasClassifier(built_cross_classifier())

In [31]:
estimator = classifier
param_grid = {'batch_size':[10,32], 'epochs':[50,100],'optimizer':['adam','rmsprop']}

In [ ]:
from sklearn.model_selection import GridSearchCV
hp = GridSearchCV(estimator , param_grid, scoring= 'accuracy', cv=5)

hpt= hp.fit(X_train,y_train)

Epoch 1/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7825 - loss: 0.5912
Epoch 2/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8043 - loss: 0.4151
Epoch 3/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8019 - loss: 0.4074
Epoch 4/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7976 - loss: 0.4224  
Epoch 5/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8319 - loss: 0.4025  
Epoch 6/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 979us/step - accuracy: 0.8295 - loss: 0.3951
Epoch 7/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8390 - loss: 0.3811
Epoch 8/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8534 - loss: 0.3639
Epoch 9/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 893us/step - accuracy: 0.8446 - loss: 0.3751
Epoch 10/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.8585 - loss: 0.3588
Epoch 11/50
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 924us/step - accuracy: 0.8478 - loss: 0.3643
Epoch 12/50
640/640 ━━━━━━━━━━━━━━━━━━━━

In [33]:
hpt.best_params_

{'batch_size': 10, 'epochs': 50, 'optimizer': 'rmsprop'}

In [34]:
hpt.best_score_

0.83475